runtime: python39

env_variables:
  MONGO_URI: mongodb+srv://playon:JYWfDwacIwN6d5hR@cluster0.upzxt.mongodb.net/playon?retryWrites=true&w=majority&appName=Cluster0
  YOUTUBE_API_KEY: AIzaSyCzYtx6oT8nTPoF8W4EZPPAca9t_yBWWlg

handlers:
- url: /.*
  script: auto